apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-exporter
  namespace: go-exporter
  labels:
    app: go-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-exporter
  template:
    metadata:
      labels:
        app: go-exporter
      annotations:
        prometheus.io/port: "2112"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: go-exporter
        image: tusharkapadi1/go-exporter:6.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent
        